# docker-compose.mongo.dev.yml
services:
  mongodb:
    image: mongo:latest
    networks:
      - myapp-network
    # Base environment variables (can be overridden)
    ports:
      - "27017:27017" # Expose for easy local access
    environment:
      MONGO_INITDB_DATABASE: myappdb
    volumes:
      - mongodb_dev_data:/data/db # Dev-specific volume, perhaps not as robust
    healthcheck:
      test: ["CMD-SHELL", "mongosh --host 127.0.0.1 --port 27017 --eval 'db.adminCommand(\"ping\").ok' --quiet"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 15s


  # http://localhost:8081/
  # admin / pass
  mongo-express:
    image: mongo-express
    networks:
      - myapp-network
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_AUTH_PASSWORD:
      ME_CONFIG_MONGODB_AUTH_USERNAME:
      ME_CONFIG_MONGODB_AUTH_DATABASE: 'myappdb'
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongodb_dev_data:

networks:
  myapp-network:
    driver: bridge